version: "3.8"
services:
  sqldb:
    image: mariadb:11.0.2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootPassword1234
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
